#!/bin/sh

PRJ_C64_DIR=$(dirname $0)

usage() {
    echo ""
    echo "Usage:"
    echo "p64 <command>"
    echo ""
    echo "commands are :"
    echo "   init                Initialise a new C64 Project."
    echo "   init project        Create the project structure (source and build directory)"
    echo "   init makefile       Create the Makefile."
    echo "   init git            Initialise git"
    echo "   init vscode         Initialise vscode configuration"
}

main() {
    if [ $# -lt 1 ]; then
        usage
        exit 0
    fi

    COMMAND=$1; shift
	if [ ! -e "$PRJ_C64_DIR/p64-$COMMAND" ]; then
        echo "command '$COMMAND' unknown."
		usage
		exit 1
	fi

    . $PRJ_C64_DIR/p64-$COMMAND $@
}

main $@